version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bankingapp-postgres
    environment:
      POSTGRES_DB: aegis_support
      POSTGRES_USER: aegis_user
      POSTGRES_PASSWORD: aegis_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aegis_user -d aegis_support"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bankingapp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: bankingapp-backend
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: aegis_user
      DB_PASSWORD: aegis_password
      DB_NAME: aegis_support
      REDIS_HOST: redis
      REDIS_PORT: 6379
      API_KEY_SECRET: aegis_secret_key_development
      # LLM Configuration (set to 'true' to enable Groq LLM features)
      LLM_ENABLED: false
      LLM_PROVIDER: groq
      LLM_FALLBACK_MODE: deterministic
      GROQ_API_KEY: ${GROQ_API_KEY:-}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: bankingapp-frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:
